package com.faceattend_edu.identity_service.application.usecase;

import com.faceattend_edu.identity_service.application.port.in.CreateUserUseCase;
import com.faceattend_edu.identity_service.application.port.out.HashPasswordPort;
import com.faceattend_edu.identity_service.application.port.out.LoadPersonPort;
import com.faceattend_edu.identity_service.application.port.out.LoadUserByUsernamePort;
import com.faceattend_edu.identity_service.application.port.out.SaveUserPort;
import com.faceattend_edu.identity_service.domain.exception.DuplicateEntityException;
import com.faceattend_edu.identity_service.domain.exception.EntityNotFoundException;
import com.faceattend_edu.identity_service.domain.model.User;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.UUID;

@RequiredArgsConstructor
@Service
public class CreateUserUseCaseImpl implements CreateUserUseCase {

    private final SaveUserPort saveUserPort;
    private final LoadPersonPort loadPersonPort;
    private final LoadUserByUsernamePort loadUserByUsernamePort;
    private final HashPasswordPort hashPasswordPort;

    @Override
    @Transactional
    public User createUser(User user, String rawPassword) {
        if (user == null || user.getPersonId() == null || user.getPersonId().getPersonId() == null) {
            throw new IllegalArgumentException("User.personId is required");
        }
        if (rawPassword == null || rawPassword.isBlank()) {
            throw new IllegalArgumentException("User.password is required");
        }

        UUID personId = user.getPersonId().getPersonId();
        if (loadPersonPort.loadPerson(personId) == null) {
            throw new EntityNotFoundException("Person", personId);
        }

        // user_id is generated by Hibernate (@GeneratedValue UUID); assigning it here would
        // make Spring Data treat the aggregate as detached and merge instead of persist.
        if (user.getAuthenticationType() == null) user.setAuthenticationType(User.DEFAULT_AUTHENTICATION_TYPE);
        user.setPasswordHash(hashPasswordPort.hash(rawPassword));
        user.validate();

        if (loadUserByUsernamePort.loadUserByUsername(user.getUsername()) != null) {
            throw new DuplicateEntityException("User", user.getUsername());
        }

        user.setStatus(true);
        user.setCreatedAt(LocalDateTime.now());
        return saveUserPort.saveUser(user);
    }
}
