server:
  port: 8081
spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/faceattend_db
    username: postgres
    password: postgres
    hikari:
      schema: identity
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: identity
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: identity
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
