// ============================================================
//  FaceAttend EDU — Catálogo canónico de endpoints del backend
//
//  Fuente de verdad para el frontend. Rutas verificadas contra:
//  - back-end/01..09 controllers/routers (Java/Fastify/FastAPI/Go)
//  - back-end/99-api-gateway/kong/kong.yml (prefijo /api/v1)
//  Todas las rutas se consumen a través del gateway Kong :8080.
// ============================================================

export const API_V1 = "/api/v1";

export const endpoints = {
    health: "/health",
    identity: {
        login: `${API_V1}/auth/login`,
        logout: `${API_V1}/auth/logout`,
        forgotPassword: `${API_V1}/auth/forgot-password`,
        verifyCode: `${API_V1}/auth/verify-code`,
        resetPassword: `${API_V1}/auth/reset-password`,
        me: `${API_V1}/auth/me`,
        persons: `${API_V1}/persons`,
        personById: (id) => `${API_V1}/persons/${id}`,
        personStatus: (id) => `${API_V1}/persons/${id}/status`,
        users: `${API_V1}/users`,
        userById: (id) => `${API_V1}/users/${id}`,
        userActivate: (id) => `${API_V1}/users/${id}/activate`,
        userStatus: (id) => `${API_V1}/users/${id}/status`,
        sessions: `${API_V1}/sessions`,
        sessionById: (id) => `${API_V1}/sessions/${id}`,
        sessionsByUser: (userId) => `${API_V1}/sessions/user/${userId}`,
        passwordPolicies: `${API_V1}/password-policies`,
        passwordPolicyById: (id) => `${API_V1}/password-policies/${id}`,
    },
    authorization: {
        roles: `${API_V1}/roles`,
        roleById: (id) => `${API_V1}/roles/${id}`,
        rolePermissions: (roleId) => `${API_V1}/roles/${roleId}/permissions`,
        rolePermission: (roleId, permId) => `${API_V1}/roles/${roleId}/permissions/${permId}`,
        permissions: `${API_V1}/permissions`,
        permissionById: (id) => `${API_V1}/permissions/${id}`,
        userRoles: (userId) => `${API_V1}/users/${userId}/roles`,
        userRolesBatch: `${API_V1}/user-roles`,
        userRole: (userId, roleId) => `${API_V1}/users/${userId}/roles/${roleId}`,
        evaluate: `${API_V1}/auth/evaluate`,
    },
    academic: {
        schools: `${API_V1}/schools`,
        schoolById: (id) => `${API_V1}/schools/${id}`,
        schoolStatus: (id) => `${API_V1}/schools/${id}/status`,
        schoolPrograms: (schoolId) => `${API_V1}/schools/${schoolId}/programs`,
        schoolPeriods: (schoolId) => `${API_V1}/schools/${schoolId}/periods`,
        schoolActors: (schoolId) => `${API_V1}/schools/${schoolId}/actors`,
        programs: `${API_V1}/programs`,
        programById: (id) => `${API_V1}/programs/${id}`,
        programCohorts: (programId) => `${API_V1}/programs/${programId}/cohorts`,
        programCourses: (programId) => `${API_V1}/programs/${programId}/courses`,
        periods: `${API_V1}/academic-periods`,
        periodById: (id) => `${API_V1}/academic-periods/${id}`,
        cohorts: `${API_V1}/cohorts`,
        cohortById: (id) => `${API_V1}/cohorts/${id}`,
        cohortEnrollments: (cohortId) => `${API_V1}/cohorts/${cohortId}/enrollments`,
        courses: `${API_V1}/courses`,
        courseById: (id) => `${API_V1}/courses/${id}`,
        actorTypes: `${API_V1}/actor-types`,
        actorTypeById: (id) => `${API_V1}/actor-types/${id}`,
        actors: `${API_V1}/academic-actors`,
        actorsByPerson: (personId) => `${API_V1}/academic-actors?personId=${personId}`,
        actorById: (id) => `${API_V1}/academic-actors/${id}`,
        actorStatus: (id) => `${API_V1}/academic-actors/${id}/status`,
        actorEnrollments: (actorId) => `${API_V1}/academic-actors/${actorId}/enrollments`,
        enrollments: `${API_V1}/enrollments`,
        enrollmentById: (id) => `${API_V1}/enrollments/${id}`,
        enrollmentStatus: (id) => `${API_V1}/enrollments/${id}/status`,
    },
    scheduling: {
        environments: `${API_V1}/environments`,
        environmentById: (id) => `${API_V1}/environments/${id}`,
        blocks: `${API_V1}/schedule-blocks`,
        blockById: (id) => `${API_V1}/schedule-blocks/${id}`,
        sessions: `${API_V1}/class-sessions`,
        sessionById: (id) => `${API_V1}/class-sessions/${id}`,
        sessionOpen: (id) => `${API_V1}/class-sessions/${id}/open`,
        sessionClose: (id) => `${API_V1}/class-sessions/${id}/close`,
        sessionCancel: (id) => `${API_V1}/class-sessions/${id}/cancel`,
        cohortBlocks: (id) => `${API_V1}/cohorts/${id}/blocks`,
        environmentBlocks: (id) => `${API_V1}/environments/${id}/blocks`,
        actorBlocks: (id) => `${API_V1}/actors/${id}/blocks`,
        blockSessions: (id) => `${API_V1}/blocks/${id}/sessions`,
    },
    attendance: {
        records: `${API_V1}/attendance-records`,
        recordById: (id) => `${API_V1}/attendance-records/${id}`,
        recordsBulk: `${API_V1}/attendance-records/bulk`,
        recordsSummary: `${API_V1}/attendance-records/summary`,
        justifications: `${API_V1}/justifications`,
        justificationById: (id) => `${API_V1}/justifications/${id}`,
        justificationReview: (id) => `${API_V1}/justifications/${id}/review`,
        justificationTypes: `${API_V1}/justification-types`,
        justificationTypeById: (id) => `${API_V1}/justification-types/${id}`,
        supportingDocuments: `${API_V1}/supporting-documents`,
        supportingDocumentById: (id) => `${API_V1}/supporting-documents/${id}`,
        sessionAttendance: (id) => `${API_V1}/class-sessions/${id}/attendance`,
        actorAttendance: (actorId) => `${API_V1}/academic-actors/${actorId}/attendance`,
        attendanceJustification: (id) => `${API_V1}/attendance/${id}/justification`,
        justificationDocuments: (id) => `${API_V1}/justifications/${id}/documents`,
    },
    biometric: {
        health: `${API_V1}/biometric/health`,
        facialEnroll: `${API_V1}/biometric/facial/enroll`,
        facialVerify: `${API_V1}/biometric/facial/verify`,
        facialIdentify: `${API_V1}/biometric/facial/identify`,
        facialByPerson: (personId) => `${API_V1}/biometric/facial/${personId}`,
        facialHistory: (personId) => `${API_V1}/biometric/facial/${personId}/history`,
        fingerprintEnroll: `${API_V1}/biometric/fingerprint/enroll`,
        fingerprintVerify: `${API_V1}/biometric/fingerprint/verify`,
        fingerprintIdentify: `${API_V1}/biometric/fingerprint/identify`,
        fingerprintsByPerson: (personId) => `${API_V1}/biometric/fingerprint/${personId}`,
        fingerprintByPersonFinger: (personId, finger) => `${API_V1}/biometric/fingerprint/${personId}/${finger}`,
        updateRequest: `${API_V1}/biometric/update-request`,
        updateRequestsByPerson: (personId) => `${API_V1}/biometric/update-requests/${personId}`,
        reviewUpdateRequest: (requestId) => `${API_V1}/biometric/update-request/${requestId}/review`,
        // Captura biométrica (rostro/huella desde imagen cruda), fusionada desde
        // 10-ms-face-auth. person_id, no username: este servicio no tiene
        // identidad propia, opera sobre personas ya conocidas por Identity/Academic.
        facialLivenessChallenge: `${API_V1}/biometric/facial/liveness-challenge`,
        facialLivenessStep: `${API_V1}/biometric/facial/liveness-step`,
        facialEnrollImage: `${API_V1}/biometric/facial/enroll-image`,
        facialIdentifyImage: `${API_V1}/biometric/facial/identify-image`,
        fingerprintEnrollSample: `${API_V1}/biometric/fingerprint/enroll-sample`,
        fingerprintIdentifySample: `${API_V1}/biometric/fingerprint/identify-sample`,
        summaryByPerson: (personId) => `${API_V1}/biometric/${personId}/summary`,
    },
    configuration: {
        academic: `${API_V1}/configurations/academic`,
        academicById: (id) => `${API_V1}/configurations/academic/${id}`,
        security: `${API_V1}/configurations/security`,
        securityById: (id) => `${API_V1}/configurations/security/${id}`,
        schoolConfigurations: (schoolId) => `${API_V1}/schools/${schoolId}/configurations`,
        biometricCases: `${API_V1}/biometric-update-cases`,
        biometricCaseById: (id) => `${API_V1}/biometric-update-cases/${id}`,
        biometricCaseReview: (id) => `${API_V1}/biometric-update-cases/${id}/review`,
        personBiometricCases: (personId) => `${API_V1}/persons/${personId}/biometric-cases`,
    },
    notification: {
        alerts: `${API_V1}/alerts`,
        alertById: (id) => `${API_V1}/alerts/${id}`,
        alertResolve: (id) => `${API_V1}/alerts/${id}/resolve`,
        alertTypes: `${API_V1}/alert-types`,
        alertTypeById: (id) => `${API_V1}/alert-types/${id}`,
    },
    quality: {
        characteristics: `${API_V1}/quality/characteristics`,
        evaluations: `${API_V1}/quality/evaluations`,
        evaluationById: (id) => `${API_V1}/quality/evaluations/${id}`,
        serviceSummary: (service) => `${API_V1}/quality/services/${encodeURIComponent(service)}/summary`,
        processProfile: `${API_V1}/quality/process/profile`,
        projects: `${API_V1}/quality/projects`,
        projectById: (id) => `${API_V1}/quality/projects/${id}`,
        projectSummary: (id) => `${API_V1}/quality/projects/${id}/summary`,
        assessments: `${API_V1}/quality/assessments`,
        assessmentById: (id) => `${API_V1}/quality/assessments/${id}`,
        istqbCategories: `${API_V1}/quality/istqb/categories`,
        istqbAssessments: `${API_V1}/quality/istqb/assessments`,
        istqbAssessmentById: (id) => `${API_V1}/quality/istqb/assessments/${id}`,
        istqbServiceSummary: (service) =>
            `${API_V1}/quality/istqb/services/${encodeURIComponent(service)}/summary`,
    },
};
