import type { AcademicActorType } from '../../../domain/entities/AcademicActorType';
import type { IAcademicActorTypeRepository } from '../../../domain/ports/out/IAcademicActorTypeRepository';
import { PostgresCrudRepository, type FieldSpec } from './crud.repository';
import { AUDIT_FIELDS } from './audit.fields';

/**
 * PostgreSQL adapter for `academic.academic_actor_type` (catálogo STUDENT/INSTRUCTOR).
 *
 * `actor_type_id` is SMALLINT GENERATED BY DEFAULT AS IDENTITY, so INSERT omits it
 * and lets the database assign the next value. Liquibase seeds 1=STUDENT and
 * 2=INSTRUCTOR — the HTTP layer no longer seeds anything at module load.
 */
export class PostgresAcademicActorTypeRepository
  extends PostgresCrudRepository<AcademicActorType>
  implements IAcademicActorTypeRepository
{
  protected readonly qualifiedTable = 'academic.academic_actor_type';
  protected readonly primaryKeyColumn = 'actor_type_id';
  protected readonly primaryKeyField = 'actorTypeId';
  protected readonly fields: readonly FieldSpec[] = [
    { field: 'actorTypeId', column: 'actor_type_id', writable: false },
    { field: 'code', column: 'code' },
    { field: 'name', column: 'name' },
    ...AUDIT_FIELDS,
  ];
}
