import { StyleSheet, Platform } from 'react-native';

const stylescommon = StyleSheet.create({
    container: {
        alignSelf: "center",
        overflow: "hidden",
    },
    image: {
        width: "100%",
        height: "100%",
    },
    containerCustomTabs: {
        flexDirection: "row",
        justifyContent: "center",
        ...(Platform.OS === "android" && { paddingTop: 40 }),
    },
    buttonCustomTabs: {
        backgroundColor: "#D9D9D9",
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 20,
        marginHorizontal: 5,
    },
    activeButtonCustomTabs: {
        backgroundColor: "#41c0ff",
    },
    textCustomTabs: {
        color: "#000",
        fontWeight: "500",
    },
    activeTextCustomTabs: {
        fontWeight: "bold",
    },
    selectorContainer: {
        marginBottom: 20,
    },
    selectorLabelSelector: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
        marginBottom: 12,
    },
    optionsContainerSelector: {
        gap: 10,
    },
    optionSelector: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: "#F9F9F9",
        borderWidth: 1,
        borderColor: "#E0E0E0",
    },
    optionSelected: {
        backgroundColor: "#E3F2FD",
        borderColor: "#007AFF",
    },
    radioContainerSelector: {
        marginRight: 12,
    },
    radioOuterSelector: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#999",
        justifyContent: "center",
        alignItems: "center",
    },
    radioOuterSelected: {
        borderColor: "#007AFF",
    },
    radioInnerSelector: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#007AFF",
    },
    optionTextSelector: {
        fontSize: 14,
        color: "#555",
        flex: 1,
    },
    optionTextSelected: {
        color: "#007AFF",
        fontWeight: "500",
    },
    progressContainer: {
        marginBottom: 20,
    },
    progressText: {
        fontSize: 12,
        color: "#666",
        marginBottom: 5,
    },
    progressBar: {
        height: 4,
        backgroundColor: "#E0E0E0",
        borderRadius: 2,
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#007AFF",
        borderRadius: 2,
    },
    navBarContainer: {
        position: "absolute",
        bottom: 20,
        left: 20,
        right: 20,
        height: 70,
        backgroundColor: "#EDEDED",
        borderRadius: 20,
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        elevation: 5,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
    },
    navButton: {
        alignItems: "center",
        justifyContent: "center",
        padding: 10,
        borderRadius: 18,
    },
    activeNavButton: {
        backgroundColor: "#d9f4ff",
    },
    navIcon: {
        width: 28,
        height: 28,
        tintColor: "#000",
    },
    navIconCenter: {
        width: 40,
        height: 40,
        tintColor: "#000",
    },
    ScrollViewWrapper: {
        flex: 1,
    },
    contentContainerScroll: {
        flexGrow: 1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    separador: {
        height: 1,
        backgroundColor: '#b4b4b4',
        marginVertical: 10,
        width: '100%',
    },
    languageOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    languageModal: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        width: '80%',
    },
    languageTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    languageOption: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
    },
    languageSelectedOption: {
        backgroundColor: '#e0f7fa',
    },
    languageOptionText: {
        fontSize: 16,
    },
    languageCloseButton: {
        marginTop: 20,
        padding: 10,
        backgroundColor: '#ccc',
        borderRadius: 5,
        alignItems: 'center',
    },
    languageCloseText: {
        fontSize: 16,
    },
    questionInput: {
        borderWidth: 1,
        borderColor: "#E0E0E0",
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        backgroundColor: "#F9F9F9",
        marginBottom: 8,
    },
    hintText: {
        fontSize: 12,
        color: "#999",
        marginBottom: 20,
        fontstyle: "italic",
    },
    rhSelectorContainer: {
        marginBottom: 20,
    },
    rhSelectorLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
        marginBottom: 12,
    },
    rhGridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 10,
    },
    rhOption: {
        width: "23%",
        backgroundColor: "#F9F9F9",
        borderWidth: 1,
        borderColor: "#E0E0E0",
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    rhOptionSelected: {
        backgroundColor: "#007AFF",
        borderColor: "#007AFF",
    },
    rhOptionText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
    },
    rhOptionTextSelected: {
        color: "#FFF",
    },
    questionnaireModalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    questionnaireModalContainer: {
        backgroundColor: "#FFF",
        borderRadius: 15,
        padding: 20,
        width: "90%",
        maxWidth: 400,
        maxHeight: "85%",
    },
    questionnaireModalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#1a1a1a",
        marginBottom: 15,
        textAlign: "center",
    },
    questionnaireQuestion: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        marginBottom: 15,
    },
    questionnaireButtonsContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 10,
        marginTop: 20,
    },
    questionnaireButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    questionnairePreviousButton: {
        backgroundColor: "#F5F5F5",
        borderWidth: 1,
        borderColor: "#E0E0E0",
    },
    questionnairePreviousButtonText: {
        color: "#666",
        fontSize: 14,
        fontWeight: "600",
    },
    questionnaireNextButton: {
        backgroundColor: "#007AFF",
    },
    questionnaireNextButtonText: {
        color: "#FFF",
        fontSize: 14,
        fontWeight: "600",
    },
    facialModalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    facialModalContainer: {
        backgroundColor: "#FFF",
        borderRadius: 15,
        padding: 20,
        width: "90%",
        maxWidth: 400,
        maxHeight: "80%",
    },
    facialModalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#1a1a1a",
        marginBottom: 10,
        textAlign: "center",
    },
    facialModalSubtitle: {
        fontSize: 14,
        color: "#666",
        textAlign: "center",
        marginBottom: 20,
        lineHeight: 20,
        fontstyle: "italic",
    },
    facialSelectLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
        marginBottom: 15,
    },
    facialChangeOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 10,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        borderRadius: 8,
        backgroundColor: "#FFF",
    },
    facialChangeOptionSelected: {
        borderColor: "#007AFF",
        backgroundColor: "#F0F8FF",
    },
    facialRadioCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#007AFF",
        marginRight: 12,
        justifyContent: "center",
        alignItems: "center",
    },
    facialRadioSelected: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#007AFF",
    },
    facialChangeLabel: {
        fontSize: 14,
        color: "#333",
        flex: 1,
    },
    facialModalButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 10,
        marginTop: 20,
    },
    facialModalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    facialCancelModalButton: {
        backgroundColor: "#F5F5F5",
        borderWidth: 1,
        borderColor: "#E0E0E0",
    },
    facialCancelModalButtonText: {
        color: "#666",
        fontSize: 14,
        fontWeight: "600",
    },
    facialConfirmModalButton: {
        backgroundColor: "#007AFF",
    },
    facialConfirmModalButtonText: {
        color: "#FFF",
        fontSize: 14,
        fontWeight: "600",
    },
    overlayTerminos: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    modalContainerTerminos: {
        width: '100%',
        maxHeight: '80%',
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 20,
    },
    titleTerminos: {
        fontSize: 20,
        fontWeight: '700',
        color: '#0B5FA5',
        marginBottom: 16,
        textAlign: 'center',
    },
    contentTerminos: {
        marginBottom: 20,
    },
    paragraphTerminos: {
        fontSize: 17,
        color: '#374151',
        marginBottom: 14,
        lineHeight: 24,
    },
    buttonTerminos: {
        backgroundColor: '#118FC3',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
    },
    buttonTextTerminos: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    subtitleTerminos: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0B5FA5',
    },
    containerSelectable: {
        flexDirection: 'row',
        alignItems: 'left',
        paddingVertical: 12,
        marginTop: 10,
        alignSelf: 'left',
    },
    checkboxSelectable: {
        width: 24,
        height: 24,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#1081D2',
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    checkboxCheckedSelectable: {
        backgroundColor: '#1081D2',
    },
    checkboxDisabledSelectable: {
        opacity: 0.5,
    },
    checkmarkSelectable: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    textSelectable: {
        color: '#333333',
        fontSize: 16,
        fontWeight: '500',
    },
    textDisabledSelectable: {
        opacity: 0.5,
    },
    containerDisabledSelectable: {
        opacity: 0.6,
    },
});

export default stylescommon;