CREATE OR REPLACE PROCEDURE delete_Tables()
LANGUAGE plpgsql
AS $$
BEGIN
    -- Primero eliminar tablas intermedias y dependientes
    DROP TABLE IF EXISTS "Log" CASCADE;
    DROP TABLE IF EXISTS "Justification" CASCADE;
    DROP TABLE IF EXISTS "Attendance" CASCADE;
    DROP TABLE IF EXISTS "Enrollment" CASCADE;
    DROP TABLE IF EXISTS "Schedule" CASCADE;
    DROP TABLE IF EXISTS "View_Action" CASCADE;
    DROP TABLE IF EXISTS "View_Module" CASCADE;
    DROP TABLE IF EXISTS "Role_Module" CASCADE;
    DROP TABLE IF EXISTS "User_Role" CASCADE;
    DROP TABLE IF EXISTS "Person_Parameters" CASCADE;
    DROP TABLE IF EXISTS "IoT_Device" CASCADE;
    DROP TABLE IF EXISTS "User" CASCADE;
    DROP TABLE IF EXISTS "Course" CASCADE;
    DROP TABLE IF EXISTS "Classroom" CASCADE;
    DROP TABLE IF EXISTS "Action" CASCADE;
    DROP TABLE IF EXISTS "View" CASCADE;
    DROP TABLE IF EXISTS "Module" CASCADE;
    DROP TABLE IF EXISTS "Role" CASCADE;
    DROP TABLE IF EXISTS "Language" CASCADE;
    DROP TABLE IF EXISTS "Person" CASCADE;
END;
$$;