package com.faceattend_edu.identity_service.domain.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserSession {

    /** Matches the PostgreSQL enum identity.user_session_status ('Active', 'Closed'). */
    public static final String STATUS_ACTIVE = "Active";
    public static final String STATUS_CLOSED = "Closed";

    private UUID sessionId;
    private User userId;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    private String sourceIp;
    private String sessionStatus;

    public void start() {
        // session_id is generated by Hibernate (@GeneratedValue UUID); assigning it here would
        // make Spring Data treat the entity as detached and merge instead of persist.
        this.startDate = LocalDateTime.now();
        this.endDate = null;
        this.sessionStatus = STATUS_ACTIVE;
    }

    public void end() {
        this.endDate = LocalDateTime.now();
        this.sessionStatus = STATUS_CLOSED;
    }

    public boolean isActive() {
        return STATUS_ACTIVE.equals(this.sessionStatus) && this.endDate == null;
    }

    public long durationSeconds() {
        if (this.startDate == null) return 0L;
        LocalDateTime end = this.endDate == null ? LocalDateTime.now() : this.endDate;
        return Math.max(0, Duration.between(this.startDate, end).getSeconds());
    }
}
