spring.application.name=faceattend-edu

spring.datasource.url=jdbc:postgresql://localhost:5433/faceattend_edu
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.open-in-view=false